FROM tensorflow/tensorflow:2.12.0-gpu

WORKDIR /usr/src/app

COPY requirements.txt .

RUN set -ex \
    && apt-get update \
    && apt-get install -y cmake libgl1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && grep -v faiss requirements.txt > requirements-gpu.txt \
    && echo  faiss-gpu >> requirements-gpu.txt \
    && echo  onnxruntime-gpu==1.15.0 >> requirements-gpu.txt \
    && pip3 install --upgrade pip \
    && pip3 install -r requirements-gpu.txt \
    && rm -r ~/.cache

COPY *.py .

EXPOSE 80

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
