FROM 732469118990.dkr.ecr.ap-northeast-1.amazonaws.com/tensorflow:2.19.1-cuda12.6

WORKDIR /usr/src/app

COPY requirements.txt .

RUN set -eu \
  && mkdir ./model \
  && pip3 install --no-cache-dir --upgrade pip \
  && pip3 install --no-cache-dir -r requirements.txt \
  && pip3 install --no-cache-dir onnxruntime-gpu

COPY . .

EXPOSE 80

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
