FROM 732469118990.dkr.ecr.ap-northeast-1.amazonaws.com/tensorflow:2.19.1-cuda12.6

WORKDIR /usr/src/app

COPY requirements.txt .

# onnxruntime-gpuはCUDA12で動くver 1.26以下を使用
# tensorrt-cu12はver 10以下が必要
RUN set -eu \
  && mkdir ./model \
  && echo 'onnxruntime-gpu<1.27' >> requirements.txt \
  && echo 'tensorrt-cu12<11' >> requirements.txt \
  && echo faiss-gpu-cu12 >> requirements.txt \
  && pip3 install --no-cache-dir --upgrade pip \
  && pip3 install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 80

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
