## onnxruntime-openvino version 1.15.0
#FROM openvino/onnxruntime_ep_ubuntu20:2023.0.0
# onnxruntime-openvino version 1.20.0
FROM openvino/onnxruntime_ep_ubuntu20:2024.4.0

USER root

RUN set -ex \
    && groupadd -g 993 render \
    && usermod -a -G render onnxruntimedev

USER onnxruntimedev

COPY --chown=onnxruntimedev:onnxruntimedev requirements.txt ./

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/onnxruntimedev/.local/bin

RUN set -ex \
    && echo 'tensorflow==2.12.0' >> requirements.txt \
    && pip3 install --upgrade pip \
    && pip3 install -r requirements.txt \
    && rm -r ~/.cache

COPY --chown=onnxruntimedev:onnxruntimedev *.py ./

EXPOSE 80


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
