# base image: NGC tf_image(Jetpack 5.1)
FROM nvcr.io/nvidia/l4t-tensorflow:r35.3.1-tf2.11-py3

WORKDIR /usr/src/app

COPY requirements.txt .

RUN set -eu \
  && mkdir ./model \
  && pip3 install --no-cache-dir --upgrade pip \
  && pip3 install --no-cache-dir -r requirements.txt \
  && wget -q https://nvidia.box.com/shared/static/mvdcltm9ewdy2d5nurkiqorofz1s53ww.whl -O onnxruntime_gpu-1.15.1-cp38-cp38-linux_aarch64.whl \
  && pip3 install onnxruntime_gpu-1.15.1-cp38-cp38-linux_aarch64.whl \
  && rm onnxruntime_gpu-1.15.1-cp38-cp38-linux_aarch64.whl

COPY . .

EXPOSE 80

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
