FROM tensorflow/tensorflow:2.11.0

WORKDIR /usr/src/app

COPY . .

RUN mkdir ./model

RUN apt-get update
RUN apt-get install -y cmake libgl1 libglib2.0-0

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN pip3 install onnxruntime

EXPOSE 80

CMD uvicorn main:app --host 0.0.0.0 --port 80
