FROM 732469118990.dkr.ecr.ap-northeast-1.amazonaws.com/tensorflow:2.19.1-cuda12.6

WORKDIR /usr/src/app

COPY requirements.txt .
COPY requirements-cuda11.txt .

# pascal対応のためTensorRTはver 8以下
# TensorRT 8だとcuda11必要
# TensorRT 8だと，onnxruntime-gpu 1.17以下
# onnxruntime 1.17だとnumpy==2.*に対応していないため，numpy<2.0

RUN set -eu \
  && mkdir ./model \
  && echo 'onnxruntime-gpu==1.17.*' >> requirements.txt \
  && echo 'numpy<2.0' >> requirements.txt \
  && echo faiss-gpu-cu12 >> requirements.txt \
  && cat requirements-cuda11.txt >> requirements.txt \
  && pip3 install --no-cache-dir --upgrade pip \
  && pip3 install --no-cache-dir -r requirements.txt


# for tensorrt
# tensorrtインストール時に"ps"コマンドが必要
RUN set -eu \
  && apt update \
  && apt install -y procps \
  && apt clean \
  && rm -r /var/lib/apt/lists \
  && pip install --no-cache-dir 'tensorrt==8.*' \
  && apt purge -y procps \
  && apt autoremove -y \
  && ls -d /usr/local/lib/python3.11/site-packages/nvidia/*/lib > /etc/ld.so.conf.d/cuda_package.conf \
  && ls -d /usr/local/lib/python3.11/site-packages/tensorrt_libs >> /etc/ld.so.conf.d/cuda_package.conf \
  && ldconfig
ENV GLIBC_TUNABLES=glibc.rtld.execstack=2


COPY . .

EXPOSE 80

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
