FROM tensorflow/tensorflow:2.19.0

WORKDIR /usr/src/app

COPY requirements.txt .

RUN set -eu \
  && mkdir ./model \
  && pip3 install --no-cache-dir --upgrade pip \
  && pip3 install --no-cache-dir --ignore-installed -r requirements.txt \
  && pip3 install --no-cache-dir onnxruntime

COPY . .

EXPOSE 80

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
