FROM openvino/ubuntu24_runtime:2026.2.1

WORKDIR /work

USER root

COPY requirements.txt .

RUN set -eu \
  && echo faiss-cpu >> requirements.txt \
  && echo tensorflow==2.19.1 >> requirements.txt \
  && echo onnxruntime-openvino >> requirements.txt \
  && pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir --ignore-installed -r requirements.txt

COPY *.py .

EXPOSE 80

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
