# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: model
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED_CPU}
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 4Gi
              cpu: 2000m
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow.mlflow:5000
      #     volumeMounts:
      #       - mountPath: /usr/src/app/model
      #         name: model
      # volumes:
      #   - name: model
      #     persistentVolumeClaim:
      #       claimName: model
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: NodePort
  selector:
    app: ${APPLICATION_NAME}
  ports:
    - port: 80
      nodePort: ${K8S_NODEPORT}
